package dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import model.MemberRoleModel;
import model.MemberRoleModelCriteria;

public interface MemberRoleModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated
     */
    int countByExample(MemberRoleModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated
     */
    int deleteByExample(MemberRoleModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated
     */
    int insert(MemberRoleModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated
     */
    int insertSelective(MemberRoleModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated
     */
    List<MemberRoleModel> selectByExample(MemberRoleModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MemberRoleModel record, @Param("example") MemberRoleModelCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MemberRoleModel record, @Param("example") MemberRoleModelCriteria example);
}